# OpenCV Maven CircleCI 2.0 configuration file
#
version: 2
jobs:
  build:
    docker:
      - image: ricktjwong/docker-java-opencv:1.0.2

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
    
    steps:
      - checkout
      - run: 
          name: Maven tests
          command: |
            cd ~/repo && mvn package
            cd ~/repo/target && java -Djava.library.path=/opt/opencv-3.4.2/build/lib -jar pHash-1.0.0.jar
